name: Auto Approve Owners Pull Request
on:
  pull_request:
    branches: 
      - main
jobs:
  approve:
    if: |
      github.event.pull_request.user.login == vars.REPOSITORY_OWNER
      && ! github.event.pull_request.draft
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x' 

      - name: Build
        run: dotnet build NADMServerSettingForm.csproj --configuration Release

      - name: Publish
        run: dotnet publish NADMServerSettingForm.csproj --configuration Release --output ./output

      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: HelloWorldExe
          path: ./output
